// extract-frames.mjs
// Build-time step that reads the provided frames ZIP, extracts the PNG frames
// into `public/frames/`, and writes a manifest (`frames.js`) with the frame
// filenames in natural numeric order plus the total frame count.
//
// This satisfies the "determine automatically" requirement: the total frame
// count, filename pattern, ordering and filenames are all derived from the
// actual archive, not hard-coded assumptions.

import { execFileSync } from 'node:child_process';
import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = dirname(dirname(fileURLToPath(import.meta.url)));
const OUT_DIR = join(ROOT, 'public', 'frames');
mkdirSync(OUT_DIR, { recursive: true });

const PY = String.raw`
import glob, json, os, re, shutil, zipfile

zips = sorted(glob.glob('*.zip'))
if not zips:
    raise SystemExit('ERROR: no frames ZIP found in repository root')

z = zipfile.ZipFile(zips[0])

def natkey(s):
    return [int(t) if t.isdigit() else t for t in re.split(r'(\d+)', s)]

pngs = sorted(
    [n for n in z.namelist() if n.lower().endswith('.png')],
    key=natkey,
)

if not pngs:
    raise SystemExit('ERROR: no PNG frames found inside the ZIP')

out = os.path.abspath(os.path.join('public', 'frames'))
for n in pngs:
    base = os.path.basename(n)
    with z.open(n) as src, open(os.path.join(out, base), 'wb') as dst:
        shutil.copyfileobj(src, dst)

# Print the flattened, natural-sorted filename list as JSON on a single line.
print('FRAMES=' + json.dumps([os.path.basename(n) for n in pngs]))
`;

let stdout;
try {
  stdout = execFileSync('python3', ['-c', PY], {
    cwd: ROOT,
    encoding: 'utf-8',
  });
} catch (err) {
  console.error('[extract-frames] failed:', err.stderr || err.message);
  process.exit(1);
}

const line = stdout
  .split('\n')
  .map((s) => s.trim())
  .find((s) => s.startsWith('FRAMES='));
if (!line) {
  console.error('[extract-frames] unexpected output:\n', stdout);
  process.exit(1);
}

const filenames = JSON.parse(line.slice('FRAMES='.length));
const manifest = `// AUTO-GENERATED by scripts/extract-frames.mjs — do not edit by hand.
// Derived from the provided frames ZIP:
//   total frame count: ${filenames.length}
//   ordering: natural numeric sort (frame_001, frame_002, ...).
export const FRAME_FILENAMES = ${JSON.stringify(filenames, null, 2)};
export const TOTAL_FRAMES = ${filenames.length};
`;

writeFileSync(
  join(ROOT, 'src', 'components', 'SpaceshipScrollHero', 'frames.js'),
  manifest,
  'utf-8',
);

console.log(
  `[extract-frames] extracted ${filenames.length} frames into public/frames and wrote frames.js manifest.`,
);
