// extract-frames.mjs
// Build-time step that reads the provided frames ZIP, extracts the PNG frames
// into `public/frames/`, and writes two generated modules:
//
//   1. `frames.js`     — filename list (natural numeric order) + total count.
//   2. `frameData.js`  — base64 data-URI versions of EVERY frame, used as an
//                        offline fallback source so the scroll animation still
//                        runs even when network image sub-requests are blocked
//                        (e.g. inside a token-enforced preview proxy).
//
// Everything is derived from the actual archive, never hard-coded.

import { execFileSync } from 'node:child_process';
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = dirname(dirname(fileURLToPath(import.meta.url)));
const OUT_DIR = join(ROOT, 'public', 'frames');
mkdirSync(OUT_DIR, { recursive: true });

const PY = String.raw`
import glob, json, os, re, shutil, zipfile

zips = sorted(glob.glob('*.zip'))
if not zips:
    raise SystemExit('ERROR: no frames ZIP found in repository root')

z = zipfile.ZipFile(zips[0])

def natkey(s):
    return [int(t) if t.isdigit() else t for t in re.split(r'(\d+)', s)]

pngs = sorted(
    [n for n in z.namelist() if n.lower().endswith('.png')],
    key=natkey,
)

if not pngs:
    raise SystemExit('ERROR: no PNG frames found inside the ZIP')

out = os.path.abspath(os.path.join('public', 'frames'))
for n in pngs:
    base = os.path.basename(n)
    with z.open(n) as src, open(os.path.join(out, base), 'wb') as dst:
        shutil.copyfileobj(src, dst)

print('FRAMES=' + json.dumps([os.path.basename(n) for n in pngs]))
`;

let stdout;
try {
  stdout = execFileSync('python3', ['-c', PY], {
    cwd: ROOT,
    encoding: 'utf-8',
  });
} catch (err) {
  console.error('[extract-frames] failed:', err.stderr || err.message);
  process.exit(1);
}

const line = stdout
  .split('\n')
  .map((s) => s.trim())
  .find((s) => s.startsWith('FRAMES='));
if (!line) {
  console.error('[extract-frames] unexpected output:\n', stdout);
  process.exit(1);
}

const filenames = JSON.parse(line.slice('FRAMES='.length));

// ---------- frames.js manifest ----------
const manifest = `// AUTO-GENERATED by scripts/extract-frames.mjs — do not edit by hand.
// Derived from the provided frames ZIP:
//   total frame count: ${filenames.length}
//   ordering: natural numeric sort (frame_001, frame_002, ...).
export const FRAME_FILENAMES = ${JSON.stringify(filenames, null, 2)};
export const TOTAL_FRAMES = ${filenames.length};
`;
writeFileSync(
  join(ROOT, 'src', 'components', 'SpaceshipScrollHero', 'frames.js'),
  manifest,
  'utf-8',
);

// ---------- frameData.js (offline data-URI fallbacks) ----------
// Produce a compact JPEG encoding of each frame for the inlined fallback. Use
// ImageMagick if available; otherwise fall back to the original PNG bytes so
// the build still succeeds everywhere.
function hasImageMagick() {
  try {
    execFileSync('convert', ['--version'], { stdio: 'ignore' });
    return true;
  } catch {
    return false;
  }
}
const useIm = hasImageMagick();

const dataUris = filenames.map((name) => {
  const pngPath = join(OUT_DIR, name);
  const pngBytes = readFileSync(pngPath);
  if (useIm) {
    // JPEG quality 88: visually excellent at 1280x720, ~10x smaller than PNG.
    const jpg = execFileSync(
      'convert',
      [pngPath, '-strip', '-quality', '88', 'jpeg:-'],
    );
    return `data:image/jpeg;base64,${jpg.toString('base64')}`;
  }
  return `data:image/png;base64,${pngBytes.toString('base64')}`;
});

const frameData = `// AUTO-GENERATED by scripts/extract-frames.mjs — do not edit by hand.
// Base64 data-URI versions of every frame (natural numeric order), used as an
// offline/blocked-network fallback so the scroll animation always runs.
// Encoded as ${useIm ? 'JPEG (quality 88)' : 'PNG'} to keep the bundle small.
export const FRAME_DATA_URIS = ${JSON.stringify(dataUris)};
export const FRAME_DATA_MIME = '${useIm ? 'image/jpeg' : 'image/png'}';
`;
writeFileSync(
  join(ROOT, 'src', 'components', 'SpaceshipScrollHero', 'frameData.js'),
  frameData,
  'utf-8',
);

console.log(
  `[extract-frames] extracted ${filenames.length} frames, wrote frames.js + frameData.js manifest.`,
);
